# Generated by Django 5.1.4 on 2024-12-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
                ('abandoned', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.table')),
            ],
        ),
        migrations.CreateModel(
            name='BillDish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_dish', to='guest.bill')),
                ('id_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish')),
            ],
        ),
        migrations.CreateModel(
            name='BillDrink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_drink', to='guest.bill')),
                ('id_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drink')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_came', models.DateField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.bill')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.table')),
            ],
        ),
    ]
