# Generated by Django 5.1.4 on 2024-12-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
