# Generated by Django 5.1.4 on 2024-12-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='wait',
            field=models.BooleanField(default=False),
        ),
    ]
