# Generated by Django 5.1.4 on 2024-12-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_billdish_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billdish',
            old_name='out',
            new_name='isReady',
        ),
        migrations.RenameField(
            model_name='billdrink',
            old_name='out',
            new_name='isReady',
        ),
    ]
