# Generated by Django 5.1.4 on 2024-12-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_guest_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdish',
            name='out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billdrink',
            name='out',
            field=models.BooleanField(default=False),
        ),
    ]
