# Generated by Django 5.1.2 on 2024-11-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Id_Menu', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.TextField(max_length=50)),
                ('Date_of_change', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id_table', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('Menu_id_menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
    ]
