# Generated by Django 5.1.4 on 2024-12-18 19:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'No Alcohol'), (1, 'Alcohol')], default=0)),
                ('description', models.TextField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drink_pic/')),
                ('weight', models.IntegerField()),
                ('special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('ingredients', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='dish_pic/')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('portion_weight', models.IntegerField()),
                ('special', models.BooleanField(default=False)),
                ('has_allergen', models.ManyToManyField(blank=True, related_name='allergens', to='api.allergen')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('date_of_change', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('dishes', models.ManyToManyField(related_name='dishes', to='api.dish')),
                ('drinks', models.ManyToManyField(related_name='drinks', to='api.drink')),
            ],
            options={
                'ordering': ['-date_of_change'],
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone_num', models.IntegerField()),
                ('work_start', models.DateField(default=datetime.date.today)),
                ('has_table', models.ManyToManyField(related_name='tables', to='api.table')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
