# Generated by Django 5.1.2 on 2024-11-10 11:41

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('Id_waiter', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=255)),
                ('Surname', models.TextField(max_length=255)),
                ('Phone_num', models.IntegerField()),
                ('Work_start', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('Id_bill', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Full_cost', models.FloatField()),
                ('Split', models.BooleanField()),
                ('Date', models.DateField(auto_now=True)),
                ('Table_id_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.table')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('Id_dish', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField(max_length=50)),
                ('Description', models.TextField(blank=True, max_length=255)),
                ('Ingredients', models.TextField(blank=True, max_length=255)),
                ('Modify', models.BooleanField()),
                ('Image', models.ImageField(blank=True, upload_to='dish_pic/')),
                ('Cost', models.FloatField()),
                ('Has_Gluten', models.BooleanField(default=False)),
                ('Has_Skorupiaki', models.BooleanField(default=False)),
                ('Has_Jaja', models.BooleanField(default=False)),
                ('Has_Ryby', models.BooleanField(default=False)),
                ('Has_Orzeszki', models.BooleanField(default=False)),
                ('Has_Soja', models.BooleanField(default=False)),
                ('Has_Laktoza', models.BooleanField(default=False)),
                ('Has_Seler', models.BooleanField(default=False)),
                ('Has_Gorczyca', models.BooleanField(default=False)),
                ('Has_Sezam', models.BooleanField(default=False)),
                ('Has_Lubin', models.BooleanField(default=False)),
                ('Has_Mieczaki', models.BooleanField(default=False)),
                ('Portion_weight', models.IntegerField()),
                ('Special', models.BooleanField(default=False)),
                ('Menu_id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_has_Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bill')),
                ('Dish_id_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('Id_drink', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=25)),
                ('Type', models.PositiveSmallIntegerField(choices=[(0, 'No Alcohol'), (1, 'Alcohol')], default=0)),
                ('Description', models.TextField(max_length=255)),
                ('Modify', models.BooleanField(default=False)),
                ('Cost', models.FloatField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='drink_pic/')),
                ('Weight', models.IntegerField()),
                ('Special', models.BooleanField(default=False)),
                ('Menu_id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_has_Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bill')),
                ('Drink_id_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drink')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('Id_quest', models.AutoField(primary_key=True, serialize=False)),
                ('Bill_id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bill')),
                ('Table_id_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.table')),
                ('Table_menu_id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Waiter_has_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Table_id_table', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.table')),
                ('Waiter_id_waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.waiter')),
            ],
        ),
    ]
