# Generated by Django 5.1.2 on 2024-11-08 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='Menu_Id_Menu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.menu'),
        ),
    ]
