# Generated by Django 5.1.2 on 2024-11-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_waiter_bill_dish_bill_has_dish_drink_bill_has_drink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='Id_quest',
            new_name='Id_guest',
        ),
    ]
