# Generated by Django 5.1.2 on 2024-11-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_table_menu_id_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Menu_Id_Menu',
            new_name='Menu_id_menu',
        ),
    ]
