# Generated by Django 5.1.3 on 2024-11-21 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dish_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.menu'),
        ),
    ]
