# Generated by Django 5.1.2 on 2024-11-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_quest_guest_id_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='Bill_id_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bill'),
        ),
    ]
