# Generated by Django 5.1.2 on 2024-11-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_guest_bill_id_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Full_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Split',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='Bill_id_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bill'),
        ),
    ]
