# Generated by Django 5.1.2 on 2024-10-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restoration',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('numberOfTables', models.IntegerField(max_length=2)),
            ],
        ),
    ]
