# Generated by Django 5.1.2 on 2024-11-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Name',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
