# Generated by Django 5.1.2 on 2024-10-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='Id_quest',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
