# Generated by Django 5.1.2 on 2024-10-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restA', '0002_alter_guest_id_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoration',
            name='Number_of_tables',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='Number_of_seats',
            field=models.IntegerField(default=1),
        ),
    ]
