# Generated by Django 5.1.2 on 2024-10-23 10:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restA', '0002_alter_restoration_numberoftables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restoration',
            old_name='numberOfTables',
            new_name='Number_of_tables',
        ),
        migrations.RemoveField(
            model_name='restoration',
            name='name',
        ),
        migrations.AddField(
            model_name='restoration',
            name='id_Restoration',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Id_Menu', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date_of_change', models.DateField(auto_now=True)),
                ('Restoration_idRestoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restA.restoration')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id_table', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Number_of_seats', models.IntegerField()),
                ('Restoration_idRestoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restA.restoration')),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('Id_waiter', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=255)),
                ('Surname', models.TextField(max_length=255)),
                ('Phone_num', models.IntegerField()),
                ('Work_start', models.DateField(default=datetime.date.today)),
                ('Restoration_idRestoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restA.restoration')),
            ],
        ),
        migrations.AddField(
            model_name='restoration',
            name='Name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
