# Generated by Django 5.1.2 on 2024-10-29 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restA', '0004_bill_dish_bill_has_dish_drink_bill_has_drink_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Menu_Id_Menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restA.menu'),
            preserve_default=False,
        ),
    ]
